/*
File: coeffs.h
Auto-generated by fir_design.py -- do not edit by hand, regenerate instead.

PLACEHOLDER VALUES: f = 100 Hz corner frequency, Fs = 1000 Hz sample rate.
Re-run `python fir_design.py <f> <Fs>` with your lab's actual target
parameters and replace this file with the real output.
*/

#define N 8
#define NUM_COEFF 17
#define SCALE_FACTOR 635

code char h[NUM_COEFF] = {-24, -27, -20, 0, 30, 64, 96, 119, 127, 119, 96, 64, 30, 0, -20, -27, -24};
