"""
fir_design.py -- designs an ideal windowed-sinc FIR low-pass filter for the
Chapter 22 lab and writes the C coefficients to coeffs.h.

Usage:
    python fir_design.py <corner_freq_Hz> <sample_rate_Hz> [alpha]

alpha (default 1.5) trades filter length for sharpness; the book suggests
values between 1 and about 2.
"""
import sys
import numpy as np


def design(f, Fs, alpha=1.5):
    delta_f = min(2 * f, Fs - 2 * f)          # width of the narrowest feature
    N = int(np.ceil(alpha * Fs / delta_f))
    Ts = 1.0 / Fs
    k = np.arange(-N, N + 1)
    h = np.where(
        k == 0,
        2 * f / Fs,
        (2 * f / Fs) * np.sin(2 * np.pi * f * k * Ts) / (2 * np.pi * f * k * Ts),
    )
    scale_factor = 127.0 / np.max(np.abs(h))
    h_scaled = np.round(h * scale_factor).astype(int)
    return N, int(round(scale_factor)), h_scaled


def main():
    if len(sys.argv) < 3:
        print("usage: python fir_design.py <corner_freq_Hz> <sample_rate_Hz> [alpha]")
        return
    f = float(sys.argv[1])
    Fs = float(sys.argv[2])
    alpha = float(sys.argv[3]) if len(sys.argv) > 3 else 1.5

    N, scale_factor, h_scaled = design(f, Fs, alpha)
    num_coeff = 2 * N + 1
    print(f"f={f} Hz, Fs={Fs} Hz, alpha={alpha}  ->  N={N}, NUM_COEFF={num_coeff}, SCALE_FACTOR={scale_factor}")

    with open("coeffs.h", "w") as out:
        out.write("/*\nFile: coeffs.h\n")
        out.write(f"Auto-generated by fir_design.py -- f={f} Hz, Fs={Fs} Hz, alpha={alpha}\n")
        out.write("Do not edit by hand, regenerate instead.\n*/\n\n")
        out.write(f"#define N {N}\n")
        out.write(f"#define NUM_COEFF {num_coeff}\n")
        out.write(f"#define SCALE_FACTOR {scale_factor}\n\n")
        out.write(f"code char h[NUM_COEFF] = {{{', '.join(str(v) for v in h_scaled)}}};\n")

    print("Wrote coeffs.h")

    # Also remind the user to update the Timer2 reload value for the new Fs.
    Fosc = 11_059_200
    reload_val = 65536 - round(Fosc / Fs)
    print(f"Timer2 reload for Fs={Fs} Hz: RCAP2H=0x{(reload_val >> 8) & 0xFF:02X}, "
          f"RCAP2L=0x{reload_val & 0xFF:02X}  (update SetTimer2_ADC_DAC.c)")


if __name__ == "__main__":
    main()
