/*
File: peripherals.h
Header file for the FIR low-pass filter lab (Chapter 22).
Coefficients (N, NUM_COEFF, SCALE_FACTOR, h[]) are generated by fir_design.py
into coeffs.h -- do not edit coeffs.h by hand, regenerate it instead.
*/

#include "coeffs.h"

extern int idata buffer[NUM_COEFF];

sfr16 RCAP2   = 0xCA;
sfr16 ADCDATA = 0xD9;
sfr16 DAC0    = 0xF9;
sfr16 DAC1    = 0xFB;

void init_Timer2(void);
void setADC(void);
void setDAC(void);
